apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oms
  template:
    metadata:
      labels:
        app: oms
    spec:
      containers:
      - name: oms-container
        image: preethiksha/oms-app:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: oms-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: oms
